load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

cc_library(
    name = "storage",
    hdrs = ["storage.h"],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
    ],
)

cc_library(
    name = "local_storage",
    srcs = ["local_storage.cc"],
    hdrs = ["local_storage.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":storage",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
    ],
)

cc_library(
    name = "gcs_storage",
    srcs = ["gcs_storage.cc"],
    hdrs = ["gcs_storage.h"],
    visibility = ["//visibility:public"],

    deps = [
        ":storage",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings:str_format",
        "@google_cloud_cpp//:storage_grpc",
    ],
)

cc_test(
    name = "storage_test",
    srcs = ["storage_test.cc"],
    deps = [
        ":local_storage",
        ":gcs_storage",
        ":storage",
        "@abseil-cpp//absl/status",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "gcs_storage_test",
    srcs = ["gcs_storage_test.cc"],
    deps = [
        ":gcs_storage",
        "@abseil-cpp//absl/strings",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "@google_cloud_cpp//:storage_grpc_mocks",
    ],
)

cc_library(
    name = "block_mapper",
    srcs = ["block_mapper.cc"],
    hdrs = ["block_mapper.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":storage",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
    ],
)

cc_test(
    name = "block_mapper_test",
    srcs = ["block_mapper_test.cc"],
    deps = [
        ":block_mapper",
        ":local_storage",
        ":storage",
        "@abseil-cpp//absl/status",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "vfs_backend",
    srcs = ["vfs_backend.cc"],
    hdrs = ["vfs_backend.h"],
    defines = ["SQLITE_CORE"],
    visibility = ["//visibility:public"],

    deps = [
        ":block_mapper",
        ":local_storage",
        ":gcs_storage",
        ":storage",
        "@abseil-cpp//absl/status",
        "@sqlite3//:sqlite3",
        "@google_cloud_cpp//:storage_grpc",
    ],
)

cc_test(
    name = "vfs_test",
    srcs = ["vfs_test.cc"],
    deps = [
        ":vfs_backend",
        "@abseil-cpp//absl/status",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "@sqlite3//:sqlite3",
    ],
)

cc_binary(
    name = "libsqlite3_gcsvfs.so",
    srcs = [
        "extension.cc",
        "vfs_backend.cc",
        "vfs_backend.h",
    ],
    copts = [
        "-Iexternal/sqlite3+",
    ],
    linkshared = True,
    visibility = ["//visibility:public"],
    deps = [
        ":block_mapper",
        ":local_storage",
        ":gcs_storage",
        ":storage",
        "@abseil-cpp//absl/status",
        "@sqlite3//:sqlite3ext",
        "@google_cloud_cpp//:storage_grpc",
    ],
)

sh_test(
    name = "e2e_shell_test",
    srcs = ["e2e_shell_test.sh"],
    data = [
        ":libsqlite3_gcsvfs.so",
        "@sqlite3//:shell",
    ],
)

cc_test(
    name = "gcs_integration_test",
    srcs = ["gcs_integration_test.cc"],
    data = [":libsqlite3_gcsvfs.so"],
    deps = [
        "@sqlite3//:sqlite3",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
